import Head from 'next/head'
import Script from 'next/script'

// components 
import Header from '@/components/header'
import Footer from '@/components/footer'



export default function Home(props) {
    return (
        <>
            <Head>
                <title>{props.title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="container mt-4">
  
                    <Header></Header>
        

                    {/* rendering the component (child) */}
                    {props.children}

            </main>

            <Footer></Footer>

  
        </>
    )
}